### ISSUE TITLE
tof_node.py is trying to open i2c-13 which does not exist, causing duckiebot-interface to restart

### ISSUE THREAD

**Issue by mjmdavis** [duckietown/dt-duckiebot-interface#51]
I'm on DB21M. 

Here's a `docker logs duckiebot-interface` extract:

> [INFO] [1612482947.918640]: [/ducky/front_center_tof_driver_node] Initializing...
> [INFO] [1612482948.128942]: [/ducky/front_center_tof_driver_node] Health status changed [STARTING] -> [STARTED]
> Traceback (most recent call last):
>   File "/code/catkin_ws/src/dt-duckiebot-interface/packages/tof_driver/src/tof_node.py", line 152, in <module>
>     node = ToFNode()
>   File "/code/catkin_ws/src/dt-duckiebot-interface/packages/tof_driver/src/tof_node.py", line 61, in __init__
>     self._sensor.open()
>   File "/usr/local/lib/python3.8/dist-packages/dt_vl53l0x/VL53L0X.py", line 125, in open
>     self._i2c.open(bus=self._i2c_bus)
>   File "/usr/local/lib/python3.8/dist-packages/smbus2/smbus2.py", line 310, in open
>     self.fd = os.open(filepath, os.O_RDWR)
> FileNotFoundError: [Errno 2] No such file or directory: '/dev/i2c-13'

Here's the list of i2c interfaces I see:
> $ ls /dev/i2*
> /dev/i2c-0  /dev/i2c-1  /dev/i2c-2  /dev/i2c-3  /dev/i2c-4  /dev/i2c-5  /dev/i2c-6

[duckiebot-interface_log.txt](https://github.com/duckietown/dt-duckiebot-interface/files/5929308/duckiebot-interface_log.txt)

**Comment by mjmdavis** [comment]
Should it really be opening I2C bus #13? Is this a config error or are the I2C buses not coming up on my DB21M? https://github.com/duckietown/dt-duckiebot-interface/blob/daffy/packages/tof_driver/config/tof_node/front_center.yaml#L1

**Comment by mjmdavis** [comment]
@afdaniele Do you know what my next steps should be?

**Comment by Ezward** [comment]
I found the same thing.  Jetson nano can use I2C buses 0 and 1.  So the config seems incorrect, at least for a Jetson Nano.  Further the PCA9685 code and the SSD1306 OLED display code both assume I2C bus 1 and they work correctly.
